export const LOAD_DATA_START = 'LOAD_DATA_START';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAIL = 'LOAD_DATA_FAILURE';
export const LOAD_DATA_START_CAT = 'LOAD_DATA_START_CAT';
export const LOAD_DATA_SUCCESS_CAT = 'LOAD_DATA_SUCCESS_CAT';
export const LOAD_DATA_FAIL_CAT = 'LOAD_DATA_FAILURE_CAT';
